/run/initialize
/vis/open OGL
/vis/viewer/set/viewpointVector 1 0 0
/vis/drawVolume
/vis/viewer/set/autoRefresh true
#/vis/filtering/trajectories/first/addValue track_id
/vis/scene/add/trajectories smooth
#/vis/scene/add/scale 10 cm
#/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/vis/viewer/zoom 4.5
/run/beamOn 1
/vis/filtering/trajectories/create/attributeFilter first
/vis/filtering/trajectories/first/setAttribute ID
